name: Self-hosted runner test

on:
  workflow_dispatch:

jobs:
  test-on-self-hosted:
    runs-on: [self-hosted]
    steps:
      - name: Say hello
        run: echo "Hola desde un EPHEMERAL runner 🚀"

